# Generated by Django 5.2 on 2025-04-28 00:35

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='project',
            name='area',
            field=models.CharField(default='Área desconocida', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=core.models.default_end_date),
        ),
        migrations.AddField(
            model_name='project',
            name='keywords',
            field=models.CharField(default='Sin palabras clave', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='objectives',
            field=models.TextField(default='Sin objetivos'),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('investigación', 'Investigación'), ('desarrollo', 'Desarrollo')], default='investigación', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='role_required',
            field=models.CharField(blank=True, choices=[('asesor', 'Asesor'), ('colaborador', 'Colaborador')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('completed', 'Completado')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('alumno', 'Alumno'), ('profesor', 'Profesor'), ('investigador', 'Investigador'), ('externo', 'Externo')], default='alumno', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advised_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='Sin descripción'),
        ),
        migrations.AlterField(
            model_name='project',
            name='requirements',
            field=models.TextField(default='Sin requisitos'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='Sin título', max_length=100),
        ),
    ]
